import { type NextPage } from "next";
import Head from "next/head";
import Home from "~/components/Home/Home";

const IndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>RVWR</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />;
    </>
  );
};

export default IndexPage;
